# Generated by Django 4.2 on 2025-04-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=150)),
                ('qualification', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('experience', models.CharField(max_length=100)),
                ('skills_required', models.CharField(max_length=250)),
                ('salary', models.IntegerField()),
                ('published_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
